target: target_column_name

models:
  linear_model:
    type: linear

  rf_model:
    type: random_forest
    params:
      n_estimators: 100
      max_depth: 5

  xgb_model:
    type: xgboost
    params:
      n_estimators: 100
      learning_rate: 0.1